services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: orderchamp
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --log-bin-trust-function-creators=1

volumes:
  mysql_data:
